# Generated by Django 5.0.2 on 2024-03-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
