# Generated by Django 5.0.2 on 2024-04-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_eventshow_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
