# Generated by Django 5.0.2 on 2024-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('service', models.CharField(max_length=100)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_inputs', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('report_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
