# Generated by Django 5.1.1 on 2024-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
