# Generated by Django 5.1.1 on 2024-10-06 20:06

import chatbot.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatbot_prompt_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='file_type',
            field=models.CharField(choices=[('links', 'Links CSV'), ('text', 'Text CSV')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.FileField(upload_to='data_csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv']), chatbot.models.validate_file_size]),
        ),
    ]
