# Generated by Django 5.0.2 on 2024-09-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_tax_amount_invoice_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_incl_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
