# Generated by Django 5.0.2 on 2024-09-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('qr_scanner_image', models.ImageField(blank=True, null=True, upload_to='bank_details/qr_scanner/')),
                ('sign_seal_image', models.ImageField(blank=True, null=True, upload_to='bank_details/sign_seal/')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='bank_details/company_logo/')),
            ],
        ),
    ]
