# Generated by Django 5.1.1 on 2024-09-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_item_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='service_type',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=20),
        ),
    ]
